# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hal-4000-v1.ui'
#
# Created: Mon Mar 10 11:10:21 2014
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(850, 701)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(850, 701))
        MainWindow.setMaximumSize(QtCore.QSize(850, 701))
        MainWindow.setAcceptDrops(True)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "HAL-4000", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../HAL-4000.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setAcceptDrops(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.cameraFrame = QtGui.QFrame(self.centralwidget)
        self.cameraFrame.setGeometry(QtCore.QRect(240, 10, 601, 581))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraFrame.sizePolicy().hasHeightForWidth())
        self.cameraFrame.setSizePolicy(sizePolicy)
        self.cameraFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.cameraFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.cameraFrame.setObjectName(_fromUtf8("cameraFrame"))
        self.film = QtGui.QGroupBox(self.centralwidget)
        self.film.setGeometry(QtCore.QRect(0, 160, 231, 261))
        self.film.setTitle(QtGui.QApplication.translate("MainWindow", "Film", None, QtGui.QApplication.UnicodeUTF8))
        self.film.setObjectName(_fromUtf8("film"))
        self.directoryText = QtGui.QLabel(self.film)
        self.directoryText.setGeometry(QtCore.QRect(30, 60, 191, 16))
        self.directoryText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.directoryText.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.directoryText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.directoryText.setObjectName(_fromUtf8("directoryText"))
        self.filenameEdit = QtGui.QLineEdit(self.film)
        self.filenameEdit.setGeometry(QtCore.QRect(10, 102, 91, 20))
        self.filenameEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.filenameEdit.setObjectName(_fromUtf8("filenameEdit"))
        self.framesLabel = QtGui.QLabel(self.film)
        self.framesLabel.setGeometry(QtCore.QRect(10, 210, 51, 16))
        self.framesLabel.setText(QtGui.QApplication.translate("MainWindow", "Frames:", None, QtGui.QApplication.UnicodeUTF8))
        self.framesLabel.setObjectName(_fromUtf8("framesLabel"))
        self.saveMovieCheckBox = QtGui.QCheckBox(self.film)
        self.saveMovieCheckBox.setGeometry(QtCore.QRect(120, 230, 81, 19))
        self.saveMovieCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Save Movie", None, QtGui.QApplication.UnicodeUTF8))
        self.saveMovieCheckBox.setChecked(True)
        self.saveMovieCheckBox.setObjectName(_fromUtf8("saveMovieCheckBox"))
        self.sizeLabel = QtGui.QLabel(self.film)
        self.sizeLabel.setGeometry(QtCore.QRect(120, 210, 31, 16))
        self.sizeLabel.setText(QtGui.QApplication.translate("MainWindow", "Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeLabel.setObjectName(_fromUtf8("sizeLabel"))
        self.modeComboBox = QtGui.QComboBox(self.film)
        self.modeComboBox.setGeometry(QtCore.QRect(50, 150, 91, 22))
        self.modeComboBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.modeComboBox.setObjectName(_fromUtf8("modeComboBox"))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Run Till Abort", None, QtGui.QApplication.UnicodeUTF8))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Fixed Length", None, QtGui.QApplication.UnicodeUTF8))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Two Ch. Cal.", None, QtGui.QApplication.UnicodeUTF8))
        self.lengthLabel = QtGui.QLabel(self.film)
        self.lengthLabel.setGeometry(QtCore.QRect(10, 183, 46, 14))
        self.lengthLabel.setText(QtGui.QApplication.translate("MainWindow", "Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.lengthLabel.setObjectName(_fromUtf8("lengthLabel"))
        self.modeLabel = QtGui.QLabel(self.film)
        self.modeLabel.setGeometry(QtCore.QRect(10, 154, 46, 14))
        self.modeLabel.setText(QtGui.QApplication.translate("MainWindow", "Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.modeLabel.setObjectName(_fromUtf8("modeLabel"))
        self.directoryLabel = QtGui.QLabel(self.film)
        self.directoryLabel.setGeometry(QtCore.QRect(10, 40, 211, 16))
        self.directoryLabel.setText(QtGui.QApplication.translate("MainWindow", "Directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.directoryLabel.setObjectName(_fromUtf8("directoryLabel"))
        self.framesText = QtGui.QLabel(self.film)
        self.framesText.setGeometry(QtCore.QRect(47, 210, 61, 20))
        self.framesText.setText(_fromUtf8(""))
        self.framesText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.framesText.setObjectName(_fromUtf8("framesText"))
        self.sizeText = QtGui.QLabel(self.film)
        self.sizeText.setGeometry(QtCore.QRect(147, 210, 71, 20))
        self.sizeText.setText(_fromUtf8(""))
        self.sizeText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sizeText.setObjectName(_fromUtf8("sizeText"))
        self.autoShuttersCheckBox = QtGui.QCheckBox(self.film)
        self.autoShuttersCheckBox.setGeometry(QtCore.QRect(10, 230, 101, 19))
        self.autoShuttersCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Run Shutters", None, QtGui.QApplication.UnicodeUTF8))
        self.autoShuttersCheckBox.setChecked(True)
        self.autoShuttersCheckBox.setObjectName(_fromUtf8("autoShuttersCheckBox"))
        self.shuttersLabels = QtGui.QLabel(self.film)
        self.shuttersLabels.setGeometry(QtCore.QRect(10, 21, 101, 16))
        self.shuttersLabels.setText(QtGui.QApplication.translate("MainWindow", "Shutter Sequence:", None, QtGui.QApplication.UnicodeUTF8))
        self.shuttersLabels.setObjectName(_fromUtf8("shuttersLabels"))
        self.shuttersText = QtGui.QLabel(self.film)
        self.shuttersText.setGeometry(QtCore.QRect(110, 20, 111, 20))
        self.shuttersText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.shuttersText.setText(_fromUtf8(""))
        self.shuttersText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.shuttersText.setObjectName(_fromUtf8("shuttersText"))
        self.filenameLabel = QtGui.QLabel(self.film)
        self.filenameLabel.setGeometry(QtCore.QRect(20, 127, 201, 20))
        self.filenameLabel.setText(_fromUtf8(""))
        self.filenameLabel.setObjectName(_fromUtf8("filenameLabel"))
        self.indexSpinBox = QtGui.QSpinBox(self.film)
        self.indexSpinBox.setGeometry(QtCore.QRect(110, 101, 51, 22))
        self.indexSpinBox.setMinimum(1)
        self.indexSpinBox.setMaximum(9999)
        self.indexSpinBox.setObjectName(_fromUtf8("indexSpinBox"))
        self.extensionComboBox = QtGui.QComboBox(self.film)
        self.extensionComboBox.setGeometry(QtCore.QRect(170, 101, 51, 22))
        self.extensionComboBox.setObjectName(_fromUtf8("extensionComboBox"))
        self.autoIncCheckBox = QtGui.QCheckBox(self.film)
        self.autoIncCheckBox.setGeometry(QtCore.QRect(10, 79, 201, 19))
        self.autoIncCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Increment Automatically", None, QtGui.QApplication.UnicodeUTF8))
        self.autoIncCheckBox.setChecked(True)
        self.autoIncCheckBox.setObjectName(_fromUtf8("autoIncCheckBox"))
        self.lengthSpinBox = QtGui.QSpinBox(self.film)
        self.lengthSpinBox.setGeometry(QtCore.QRect(60, 180, 81, 22))
        self.lengthSpinBox.setMaximum(1000000)
        self.lengthSpinBox.setObjectName(_fromUtf8("lengthSpinBox"))
        self.notes = QtGui.QGroupBox(self.centralwidget)
        self.notes.setGeometry(QtCore.QRect(0, 580, 841, 81))
        self.notes.setTitle(QtGui.QApplication.translate("MainWindow", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.notes.setObjectName(_fromUtf8("notes"))
        self.gridLayout = QtGui.QGridLayout(self.notes)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.notesEdit = QtGui.QTextEdit(self.notes)
        self.notesEdit.setObjectName(_fromUtf8("notesEdit"))
        self.gridLayout.addWidget(self.notesEdit, 0, 0, 1, 1)
        self.recordButton = QtGui.QPushButton(self.centralwidget)
        self.recordButton.setGeometry(QtCore.QRect(240, 550, 75, 24))
        self.recordButton.setText(QtGui.QApplication.translate("MainWindow", "Record", None, QtGui.QApplication.UnicodeUTF8))
        self.recordButton.setObjectName(_fromUtf8("recordButton"))
        self.settings = QtGui.QGroupBox(self.centralwidget)
        self.settings.setGeometry(QtCore.QRect(0, 10, 231, 151))
        self.settings.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.settings.setObjectName(_fromUtf8("settings"))
        self.settingsButton1 = QtGui.QRadioButton(self.settings)
        self.settingsButton1.setGeometry(QtCore.QRect(10, 20, 211, 19))
        self.settingsButton1.setText(QtGui.QApplication.translate("MainWindow", "RadioButton", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsButton1.setObjectName(_fromUtf8("settingsButton1"))
        self.settingsButton2 = QtGui.QRadioButton(self.settings)
        self.settingsButton2.setGeometry(QtCore.QRect(10, 40, 211, 19))
        self.settingsButton2.setText(QtGui.QApplication.translate("MainWindow", "RadioButton", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsButton2.setObjectName(_fromUtf8("settingsButton2"))
        self.settingsButton3 = QtGui.QRadioButton(self.settings)
        self.settingsButton3.setGeometry(QtCore.QRect(10, 60, 211, 19))
        self.settingsButton3.setText(QtGui.QApplication.translate("MainWindow", "RadioButton", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsButton3.setObjectName(_fromUtf8("settingsButton3"))
        self.settingsButton4 = QtGui.QRadioButton(self.settings)
        self.settingsButton4.setGeometry(QtCore.QRect(10, 80, 211, 19))
        self.settingsButton4.setText(QtGui.QApplication.translate("MainWindow", "RadioButton", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsButton4.setObjectName(_fromUtf8("settingsButton4"))
        self.settingsButton5 = QtGui.QRadioButton(self.settings)
        self.settingsButton5.setGeometry(QtCore.QRect(10, 100, 211, 19))
        self.settingsButton5.setText(QtGui.QApplication.translate("MainWindow", "RadioButton", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsButton5.setObjectName(_fromUtf8("settingsButton5"))
        self.settingsButton6 = QtGui.QRadioButton(self.settings)
        self.settingsButton6.setGeometry(QtCore.QRect(10, 120, 211, 19))
        self.settingsButton6.setText(QtGui.QApplication.translate("MainWindow", "RadioButton", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsButton6.setObjectName(_fromUtf8("settingsButton6"))
        self.cameraParamsFrame = QtGui.QFrame(self.centralwidget)
        self.cameraParamsFrame.setGeometry(QtCore.QRect(-1, 419, 241, 171))
        self.cameraParamsFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.cameraParamsFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.cameraParamsFrame.setObjectName(_fromUtf8("cameraParamsFrame"))
        self.cameraShutterButton = QtGui.QPushButton(self.centralwidget)
        self.cameraShutterButton.setGeometry(QtCore.QRect(330, 550, 101, 24))
        self.cameraShutterButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cameraShutterButton.setText(QtGui.QApplication.translate("MainWindow", "Open Shutter", None, QtGui.QApplication.UnicodeUTF8))
        self.cameraShutterButton.setObjectName(_fromUtf8("cameraShutterButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "New Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionShutter = QtGui.QAction(MainWindow)
        self.actionShutter.setText(QtGui.QApplication.translate("MainWindow", "New Shutter Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShutter.setObjectName(_fromUtf8("actionShutter"))
        self.actionDirectory = QtGui.QAction(MainWindow)
        self.actionDirectory.setText(QtGui.QApplication.translate("MainWindow", "Set Working Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDirectory.setObjectName(_fromUtf8("actionDirectory"))
        self.actionIllumination = QtGui.QAction(MainWindow)
        self.actionIllumination.setText(QtGui.QApplication.translate("MainWindow", "Illumination", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIllumination.setObjectName(_fromUtf8("actionIllumination"))
        self.actionStage = QtGui.QAction(MainWindow)
        self.actionStage.setText(QtGui.QApplication.translate("MainWindow", "Stage", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStage.setObjectName(_fromUtf8("actionStage"))
        self.actionFocus_Lock = QtGui.QAction(MainWindow)
        self.actionFocus_Lock.setText(QtGui.QApplication.translate("MainWindow", "Focus Lock", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFocus_Lock.setObjectName(_fromUtf8("actionFocus_Lock"))
        self.actionSpot_Counter = QtGui.QAction(MainWindow)
        self.actionSpot_Counter.setText(QtGui.QApplication.translate("MainWindow", "Spot Counter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpot_Counter.setObjectName(_fromUtf8("actionSpot_Counter"))
        self.actionSwitch_Test = QtGui.QAction(MainWindow)
        self.actionSwitch_Test.setText(QtGui.QApplication.translate("MainWindow", "Switch Test", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSwitch_Test.setObjectName(_fromUtf8("actionSwitch_Test"))
        self.actionMisc_Controls = QtGui.QAction(MainWindow)
        self.actionMisc_Controls.setText(QtGui.QApplication.translate("MainWindow", "Misc. Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMisc_Controls.setObjectName(_fromUtf8("actionMisc_Controls"))
        self.actionProgression = QtGui.QAction(MainWindow)
        self.actionProgression.setText(QtGui.QApplication.translate("MainWindow", "Progressions", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProgression.setObjectName(_fromUtf8("actionProgression"))
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionShutter)
        self.menuFile.addAction(self.actionDirectory)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionFocus_Lock)
        self.menuFile.addAction(self.actionIllumination)
        self.menuFile.addAction(self.actionMisc_Controls)
        self.menuFile.addAction(self.actionProgression)
        self.menuFile.addAction(self.actionSpot_Counter)
        self.menuFile.addAction(self.actionStage)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

