# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'odFilters.ui'
#
# Created: Wed Oct 29 10:29:51 2014
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(511, 324)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(511, 310))
        Dialog.setMaximumSize(QtCore.QSize(840, 700))
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "HAL-4000 Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.mosaicBox = QtGui.QGroupBox(Dialog)
        self.mosaicBox.setGeometry(QtCore.QRect(10, 0, 461, 311))
        self.mosaicBox.setTitle(QtGui.QApplication.translate("Dialog", "Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.mosaicBox.setObjectName(_fromUtf8("mosaicBox"))
        self.groupBox405 = QtGui.QGroupBox(self.mosaicBox)
        self.groupBox405.setGeometry(QtCore.QRect(20, 30, 101, 141))
        self.groupBox405.setTitle(QtGui.QApplication.translate("Dialog", "405", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox405.setObjectName(_fromUtf8("groupBox405"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox405)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioButton_405_0 = QtGui.QRadioButton(self.groupBox405)
        self.radioButton_405_0.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_405_0.setObjectName(_fromUtf8("radioButton_405_0"))
        self.verticalLayout.addWidget(self.radioButton_405_0)
        self.radioButton_405_05 = QtGui.QRadioButton(self.groupBox405)
        self.radioButton_405_05.setText(QtGui.QApplication.translate("Dialog", "0.5", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_405_05.setObjectName(_fromUtf8("radioButton_405_05"))
        self.verticalLayout.addWidget(self.radioButton_405_05)
        self.radioButton_405_1 = QtGui.QRadioButton(self.groupBox405)
        self.radioButton_405_1.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_405_1.setObjectName(_fromUtf8("radioButton_405_1"))
        self.verticalLayout.addWidget(self.radioButton_405_1)
        self.radioButton_405_2 = QtGui.QRadioButton(self.groupBox405)
        self.radioButton_405_2.setText(QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_405_2.setObjectName(_fromUtf8("radioButton_405_2"))
        self.verticalLayout.addWidget(self.radioButton_405_2)
        self.radioButton_405_3 = QtGui.QRadioButton(self.groupBox405)
        self.radioButton_405_3.setText(QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_405_3.setObjectName(_fromUtf8("radioButton_405_3"))
        self.verticalLayout.addWidget(self.radioButton_405_3)
        self.radioButton_405_4 = QtGui.QRadioButton(self.groupBox405)
        self.radioButton_405_4.setText(QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_405_4.setObjectName(_fromUtf8("radioButton_405_4"))
        self.verticalLayout.addWidget(self.radioButton_405_4)
        self.groupBox488 = QtGui.QGroupBox(self.mosaicBox)
        self.groupBox488.setGeometry(QtCore.QRect(130, 30, 101, 141))
        self.groupBox488.setTitle(QtGui.QApplication.translate("Dialog", "488", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox488.setObjectName(_fromUtf8("groupBox488"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox488)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radioButton_488_0 = QtGui.QRadioButton(self.groupBox488)
        self.radioButton_488_0.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_488_0.setObjectName(_fromUtf8("radioButton_488_0"))
        self.verticalLayout_2.addWidget(self.radioButton_488_0)
        self.radioButton_488_05 = QtGui.QRadioButton(self.groupBox488)
        self.radioButton_488_05.setText(QtGui.QApplication.translate("Dialog", "0.5", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_488_05.setObjectName(_fromUtf8("radioButton_488_05"))
        self.verticalLayout_2.addWidget(self.radioButton_488_05)
        self.radioButton_488_1 = QtGui.QRadioButton(self.groupBox488)
        self.radioButton_488_1.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_488_1.setObjectName(_fromUtf8("radioButton_488_1"))
        self.verticalLayout_2.addWidget(self.radioButton_488_1)
        self.radioButton_488_2 = QtGui.QRadioButton(self.groupBox488)
        self.radioButton_488_2.setText(QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_488_2.setObjectName(_fromUtf8("radioButton_488_2"))
        self.verticalLayout_2.addWidget(self.radioButton_488_2)
        self.radioButton_488_3 = QtGui.QRadioButton(self.groupBox488)
        self.radioButton_488_3.setText(QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_488_3.setObjectName(_fromUtf8("radioButton_488_3"))
        self.verticalLayout_2.addWidget(self.radioButton_488_3)
        self.radioButton_488_4 = QtGui.QRadioButton(self.groupBox488)
        self.radioButton_488_4.setText(QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_488_4.setObjectName(_fromUtf8("radioButton_488_4"))
        self.verticalLayout_2.addWidget(self.radioButton_488_4)
        self.groupBox561 = QtGui.QGroupBox(self.mosaicBox)
        self.groupBox561.setGeometry(QtCore.QRect(240, 30, 101, 141))
        self.groupBox561.setTitle(QtGui.QApplication.translate("Dialog", "561", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox561.setObjectName(_fromUtf8("groupBox561"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox561)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.radioButton_561_0 = QtGui.QRadioButton(self.groupBox561)
        self.radioButton_561_0.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_561_0.setObjectName(_fromUtf8("radioButton_561_0"))
        self.verticalLayout_3.addWidget(self.radioButton_561_0)
        self.radioButton_561_05 = QtGui.QRadioButton(self.groupBox561)
        self.radioButton_561_05.setText(QtGui.QApplication.translate("Dialog", "0.5", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_561_05.setObjectName(_fromUtf8("radioButton_561_05"))
        self.verticalLayout_3.addWidget(self.radioButton_561_05)
        self.radioButton_561_1 = QtGui.QRadioButton(self.groupBox561)
        self.radioButton_561_1.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_561_1.setObjectName(_fromUtf8("radioButton_561_1"))
        self.verticalLayout_3.addWidget(self.radioButton_561_1)
        self.radioButton_561_2 = QtGui.QRadioButton(self.groupBox561)
        self.radioButton_561_2.setText(QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_561_2.setObjectName(_fromUtf8("radioButton_561_2"))
        self.verticalLayout_3.addWidget(self.radioButton_561_2)
        self.radioButton_561_3 = QtGui.QRadioButton(self.groupBox561)
        self.radioButton_561_3.setText(QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_561_3.setObjectName(_fromUtf8("radioButton_561_3"))
        self.verticalLayout_3.addWidget(self.radioButton_561_3)
        self.radioButton_561_4 = QtGui.QRadioButton(self.groupBox561)
        self.radioButton_561_4.setText(QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_561_4.setObjectName(_fromUtf8("radioButton_561_4"))
        self.verticalLayout_3.addWidget(self.radioButton_561_4)
        self.groupBox642 = QtGui.QGroupBox(self.mosaicBox)
        self.groupBox642.setGeometry(QtCore.QRect(350, 30, 101, 141))
        self.groupBox642.setTitle(QtGui.QApplication.translate("Dialog", "642", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox642.setObjectName(_fromUtf8("groupBox642"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox642)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.radioButton_642_0 = QtGui.QRadioButton(self.groupBox642)
        self.radioButton_642_0.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_642_0.setObjectName(_fromUtf8("radioButton_642_0"))
        self.verticalLayout_4.addWidget(self.radioButton_642_0)
        self.radioButton_642_05 = QtGui.QRadioButton(self.groupBox642)
        self.radioButton_642_05.setText(QtGui.QApplication.translate("Dialog", "0.5", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_642_05.setObjectName(_fromUtf8("radioButton_642_05"))
        self.verticalLayout_4.addWidget(self.radioButton_642_05)
        self.radioButton_642_1 = QtGui.QRadioButton(self.groupBox642)
        self.radioButton_642_1.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_642_1.setObjectName(_fromUtf8("radioButton_642_1"))
        self.verticalLayout_4.addWidget(self.radioButton_642_1)
        self.radioButton_642_2 = QtGui.QRadioButton(self.groupBox642)
        self.radioButton_642_2.setText(QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_642_2.setObjectName(_fromUtf8("radioButton_642_2"))
        self.verticalLayout_4.addWidget(self.radioButton_642_2)
        self.radioButton_642_3 = QtGui.QRadioButton(self.groupBox642)
        self.radioButton_642_3.setText(QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_642_3.setObjectName(_fromUtf8("radioButton_642_3"))
        self.verticalLayout_4.addWidget(self.radioButton_642_3)
        self.radioButton_642_4 = QtGui.QRadioButton(self.groupBox642)
        self.radioButton_642_4.setText(QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_642_4.setObjectName(_fromUtf8("radioButton_642_4"))
        self.verticalLayout_4.addWidget(self.radioButton_642_4)
        self.pushButton_reload = QtGui.QPushButton(self.mosaicBox)
        self.pushButton_reload.setGeometry(QtCore.QRect(10, 280, 75, 23))
        self.pushButton_reload.setText(QtGui.QApplication.translate("Dialog", "Reload Config", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_reload.setObjectName(_fromUtf8("pushButton_reload"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        pass

